sonar.projectKey=terraform-oidc-project
sonar.projectName=terraform-oidc-project
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=http://18.220.45.172:9000

# Terraform files
sonar.inclusions=**/*.tf

# Optional exclusions
sonar.exclusions=**/.terraform/**,**/*.md
