name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options: [dev, uat, prod]
      action:
        description: "Select Action"
        required: true
        type: choice
        options: [plan, apply, destroy]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-*.zip
          sudo mv sonar-scanner-* /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=terraform-oidc-project \
            -Dsonar.projectName=terraform-oidc-project \
            -Dsonar.sources=. \
            -Dsonar.inclusions=**/*.tf \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform init -reconfigure -upgrade

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve
